server:
  port: 8080

jwt:
  header: Authorization
  secret: gVhKcwJymrCmLFSfFSxIPctXKRsuTC

logging:
  level:
    org.springframework.security: DEBUG

spring:
  resources:
    chain:
      enabled: true